### ISSUE TITLE
Support static linking

### ISSUE THREAD

**Issue by Philipp-M** [gdesmott/system-deps#40]
I'm currently trying to figure out how to support static linking of libraries.
It seems that's a rather tricky task, as `pkg-config` doesn't seem to provide a way (at least `pub`) to check if the library is static (via `pkg_config::Config::probe`).

I've seen that `pkg_config::Config::cargo_metadata` is set to false everywhere where it is used (as this is apparently done in this lib), Is there a reason for not using `pkg-config`'s `cargo_metadata`? As setting it to `true` does have the desired effect of hinting cargo that the desired lib is static (and not printing it in this lib).

**Comment by gdesmott** [comment]
`cargo_metadata` is disabled as `system-deps` needs control on what's being exported exactly, as they can be overridden  using env variables, etc, see 331bab3e90687b3892acf2e8868668448611766b

Looking at [pkg-config-rs's code](https://github.com/rust-lang/pkg-config-rs/blob/master/src/lib.rs#L554), it looks like it's simply using `rustc-link-lib=static=` instead of `rustc-link-lib=` when doing static linking. It should be easy enough to do the same in `system-deps`.

So I guess the question here is the API we want to provide. Should we allow crate authors to request static linking in `Cargo.toml` or should this only be controlled using env variables?

**Comment by Philipp-M** [comment]
> it looks like it's simply using rustc-link-lib=static= instead of rustc-link-lib= when doing static linking. It should be easy enough to do the same in system-deps

Yes I've already experimented a little bit (hacked it into this lib), and that seems to be enough to get it running as expected (tested on iOS, Android and Linux).

> So I guess the question here is the API we want to provide. Should we allow crate authors to request static linking in Cargo.toml or should this only be controlled using env variables?

Maybe support both? So that it is easy to explicitly state it in `Cargo.toml` and be able to override it for some reason with env variables. I also think that it might be useful to be able to to this per platform like [this](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies), but I'm not sure if it's worth the amount of work, as I guess the main use-case for statically linked libs are selfcontained applications/wrapper-libs(?) around an e.g. C-lib.

There is still a question, if we should honor most of the options of pkg-config via env vars like [here](https://github.com/rust-lang/pkg-config-rs/blob/54325785816695df031cef3b26b6a9a203bbc01b/src/lib.rs#L448) as they are ignored by not using `pkg_config::Config::cargo_metadata`

**Comment by gdesmott** [comment]
> Maybe support both?

I never used static linking so I'm not sure of what the actual use cases are. But shouldn't it be the builder/packager who decides to use static linking rather than the crate author?

At the very least I think we could add support for those env variables: `SYSTEM_DEPS_$NAME_LINK=static` and `SYSTEM_DEPS_LINK=static` controlling the link mode of a single or all deps.

I'd start with that and would consider `Cargo.toml` API later on if actually needed. In which case we could then have `SYSTEM_DEPS_$NAME_LINK=dynamic` to override it.

Does that make sense? Are you interested implementing this?
It would good to also check how this interact with the current [build internal](https://docs.rs/system-deps/3.1.1/system_deps/#statically-build-system-library) feature. Actually I'm not sure if/how this one is currently statically linking.

> There is still a question, if we should honor most of the options of pkg-config via env vars like [here](https://github.com/rust-lang/pkg-config-rs/blob/54325785816695df031cef3b26b6a9a203bbc01b/src/lib.rs#L448) as they are ignored by not using `pkg_config::Config::cargo_metadata`

I'd rather have system-deps defining its own set of env variables rather than using the pkg-config-rs ones.

**Comment by lu-zero** [comment]
Recently @luni-4 tried to make binaries for something that uses C libraries and did not want to carry around all of them in the CI.

build internal should always static-linking.

**Comment by gdesmott** [comment]
@Philipp-M @lu-zero @Luni-4 : can you please try #48 and check if it fits your needs?
